FROM python:3.14-slim

WORKDIR /app

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y \
    tree \
    ffmpeg \
    curl \
    libopus-dev \
    # gcc \
    # libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia el archivo requirements del proyecto
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir davey

# Copia el código del proyecto
COPY . .

# Ejecuta código
CMD ["python", "main.py"]
