# Base Python ligera
FROM python:3.14-slim

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    tree \
    ffmpeg \
    curl \
    libopus-dev \
    # gcc \
    # libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements e instalarlos
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir davey

# Copiar el código del proyecto
COPY . .

# Ejecutar código del proyecto
CMD ["python", "main.py"]
